data <- read.table("household_power_consumption.txt", sep=";", header = TRUE, na.strings = "?", stringsAsFactors=FALSE)
gapData <- subset(data, data$Date == "1/2/2007" | data$Date == "2/2/2007")
png("plot2.png", width = 480, height = 480)
days <- strptime(paste(gapData$Date, gapData$Time), format="%d/%m/%Y %H:%M:%S")
plot(days, gapData$Global_active_power, type="l", xlab="", ylab="Global Active Power (kilowatts)")
dev.off()