data <- read.table("household_power_consumption.txt", sep=";", header = TRUE, na.strings = "?", stringsAsFactors=FALSE)
gapData <- subset(data, data$Date == "1/2/2007" | data$Date == "2/2/2007")
png("plot4.png", width = 480, height = 480)
par(mfrow = c(2, 2), mar=c(4,4,0.5,5))
plot(days, gapData$Global_active_power, type="l", xlab="", ylab="Global Active Power")
plot(days, gapData$Voltage, type="l", xlab="", ylab="Voltage")
plot(days, gapData$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(days, gapData$Sub_metering_2, col="red")
lines(days, gapData$Sub_metering_3, col="blue")
legend(x="topright",c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lwd = 1, bty = "n")
plot(days, gapData$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()