sccDS <- readRDS("./exdata-data-NEI_data/Source_Classification_Code.rds")
neiDS <- readRDS("./exdata-data-NEI_data/summarySCC_PM25.rds")
BaltimoreCityOnroad <- subset(neiDS, fips == "24510" & type == "ON-ROAD")
BaltimoreCityOnroad <- aggregate(BaltimoreCityOnroad[, "Emissions"], by=list(BaltimoreCityOnroad$year), sum)
colnames(BaltimoreCityOnroad) <- c("year", "emissions")
LAOnroad <- subset(neiDS, fips == "06037" & type == 'ON-ROAD')
LAOnroad <- aggregate(LAOnroad[, 'Emissions'], by=list(LAOnroad$year), sum)
colnames(LAOnroad) <- c('year', 'emissions')
labcEmissions <- rbind(BaltimoreCityOnroad, LAOnroad)
labcEmissions[,"city"] <- c("Baltimore City", "Baltimore City", "Baltimore City", "Baltimore City", "LA", "LA", "LA", "LA")
png(filename = "plot6.png", width = 750, height = 550, units = "px")
g = ggplot(data = labcEmissions, aes(x = year, y = emissions, color = city)) + facet_grid(. ~ city)
g + geom_line(aes(group = city)) + geom_point() + guides(fill = F) + ggtitle("Emissions from vehicle sources in Baltimore City and LA County")
dev.off()
